### ISSUE TITLE
Provide configurable serialization

### ISSUE THREAD

**Issue by jreut** [levinmr/rspec-snapshot#4]
I'm not sure I'll have time to open a PR within the next few days, so I wanted open an issue for discussion. I'll start by listing the desired features as I understand them.

## configurable serialization

This could be done globally, perhaps like

```ruby
RSpec.configure { |c| c.snapshot_serializer = :my_serializer }
```

or per-expectation like

```ruby
match_snapshot 'snapshot_file_name', serializer: :my_serializer
```

This would require a notion of serializer registration:

```ruby
RSpec::Snapshot.register_serializer :custom_serializer, CustomSnapshotSerializer
```

## default serializer

The default serializer could look like something like this:

```ruby
class DefaultSerializer
  def dump(object)
    object.to_s
  end
end
```

This illustrates the serializer API: `#dump(Object) : String`

### JSON

Ruby ships with the `json` package in the standard library, so we could use that.

### HTML

Nokogiri is a widely-used XML/HTML library, but it is an external dependency. Perhaps it would be worthwhile to extract an `rspec-snapshot-html_serializer` gem that encapsulates the dependency.

---

Do you have any opinion on these features? Again, I likely will not have time to work on a pull request until sometime next week. I just wrote this up to remember what I'd like to do.

**Comment by derekcannon** [comment]
I think it would also be nice to include hashes in the build-in serializers. This would make testing formatters/helpers very simple. Especially those that return large lists of data. From what I see, the `.snap` files are on one line. I would also appreciate hash serialization it to be multiline and human readable. This way `.snap`s could be committed and compared easily in PRs.

**Comment by rrcobb** [comment]
#8 adds some new configuration options and changes the default serializer. With a little work, I think it could use a different serializer.

It might be good (but maybe not necessary) for a serializer to support both `dump` and `load`, so that it could be used in either direction (in case, for instance, you wanted to load the output of one test as the mock for another test)

```
class DefaultSerializer
  def dump(object)
    object.to_s
  end

  def load(str)
     str.to_object # not actually a method, huh
  end
end
```

**Comment by levinmr** [comment]
done in 2.0.0
