### ISSUE TITLE
Fails if snapshot_name has forward slashes

### ISSUE THREAD

**Issue by wulffeld** [levinmr/rspec-snapshot#45]
I was using rspec-snapshot via this blog post https://www.bearer.com/blog/snapshot-testing-viewcomponents-with-rspec

This started to fail with 2.0.2. The workaround seems easy enough though:

```
config.after(:each, type: :component, snapshot: true) do |example|
  class_name = example.metadata[:described_class].name.underscore.tr("/", "_")
  test_name = example.metadata[:full_description].tr(example.metadata[:described_class].name, "").tr(" ", "_")
  raise "component snapshot has no content" if page.native.blank?

  expect(page.native).to match_snapshot("#{class_name}-#{test_name}")
end
```

## Expected behaviour

It creates the folders below __snapshot__ like <= 2.0.1 did.

**Comment by levinmr** [comment]
Thanks for bringing this to my attention.  I wasn't aware that people were creating subfolders in this way.  I'll fix the bug and note this behavior as a feature.

**Comment by colszowka** [comment]
We have a similar case in that we're using `example.full_description` sometimes to automatically derive the snapshot name from the rspec example itself, and this currently fails when you have an API path in an acceptance spec context for example

**Comment by levinmr** [comment]
Fixed in https://github.com/levinmr/rspec-snapshot/releases/tag/v2.0.3
